### ISSUE TITLE
Commit c91acbc breaks Model.save() interface

### ISSUE THREAD

**Issue by kriswill** [jeromegn/Backbone.localStorage#129]
The merged commit c91acbc breaks the default behavior of `Model.save()`.  The default behavior is for `Model.save()` to call `Model.parse(response)` with any data returned from the ajax call.  Any sub-models or collections that are produced by the `Model.parse` should be managed in the parse, I believe this patch was issued to deal with inadequate state management in Backbone-Relational.

**Comment by scott-w** [comment]
I think this code has been removed so I'm going to close this issue.
