### ISSUE TITLE
collection.remove() doesn't sync into localStorage

### ISSUE THREAD

**Issue by howtomakeaturn** [jeromegn/Backbone.localStorage#132]
I register the 'change' event:

```
this.collection.bind('change', this.refresh, this);
```

and then write the following code, which doesn't behave as expected:

```
    var item = this.collection.get(id);        
    this.collection.remove(item);
```

I observe the localStorage (with chrome developer tool), finding the localStorage doesn't change at all.
it doesn't trigger the collection 'change' event which I registered at the beginning, either.

so, instead, I use these code:

```
    var item = this.collection.get(id);
    item.destroy();
    this.render();
```

And It works as I wish!
Is there something wrong or I misunderstood the 'collection.remove' method?

Thx for any advice :D

**Comment by scott-w** [comment]
This is correct behaviour in-line with Backbone's standard behaviour.
