### ISSUE TITLE
a trouble about the fetch function

### ISSUE THREAD

**Issue by qkhhimkfrgw** [jeromegn/Backbone.localStorage#142]
Hi! Thank you for reading my problem about Backbone.localStorage.

I'm sorry to tell that may be I had found a bug.

I'm not sure if it is a bug or not, but I have a problem like this:

``` javascript
// create one record without specifing an id and the id is generated by the localStorage.guid() function
var collection = new ModelCollection();
collection.createTestData();
collection.fetch({async: false});
collection.at(0).destroy();
// create one record again
collection.createTestData();
collection.fetch({async: false});
if (collection.size() > 0) {
    collection.at(0).destroy();
} else {
    alert('data not found');
}
```

The step is that:
1. createTestData() // create one random record 
2. fetch() // the record is getted
3. destroy() // the key point!
4. createTestData() // create one random record agian
5. fetch() // fetch again, but data not found

As you see, the record won't be found in the second time if I delete records before and do not specify an id and the id is generated by the localStorage.guid() function.

How can I solve the problem? Do I have to specify one id?

**Comment by scott-w** [comment]
I'm inclined to think that this is correct behaviour - `model.destroy()` is supposed to synchronise with the server/localstorage so I'd expect `fetch` to return nothing.
