### ISSUE TITLE
"Uncaught SyntaxError: Unexpected token <"

### ISSUE THREAD

**Issue by oscaralanpierce** [jeromegn/Backbone.localStorage#158]
When I load my page, it raises an error that says `Uncaught SyntaxError: Unexpected token < backbone.localStorage-min.js:5`. I can see this is referring to the `<!DOCTYPE html>` tag. This is the code in my minimal example:

<pre><code>&lt;!DOCTYPE html&gt;
&lt;html&gt;
&lt;body&gt;
  &lt;script src='js/lib/jquery-2.1.1.js'&gt;&lt;/script&gt;
  &lt;script src='js/lib/underscore.js'&gt;&lt;/script&gt;
  &lt;script src='js/lib/backbone.js'&gt;&lt;/script&gt;
  &lt;script src='js/lib/backbone.localStorage-min.js'&gt;&lt;/script&gt;
&lt;/body&gt;
&lt;/html&gt;</code></pre>

This doesn't seem to be causing any problems other than the error being shown in the console (though I haven't been using it that long), but I'd just as soon the error didn't come up. Any thoughts? I'm sorry if this is something really simple I'm missing. I'm pretty new to front-end web development.

**Comment by BogdanTudosie** [comment]
I have a similar problem with the latest backbone.localStorage  on line 4
