### ISSUE TITLE
Failing silently when storage has been disabled

### ISSUE THREAD

**Issue by spenoir** [jeromegn/Backbone.localStorage#168]
If a user disables websites from saving data then Backbone.localStorage creates a security exception that breaks all javascript on the page. Backbone.localStorage also throws an error which also breaks all javascript on the page. 

I've created a pull request to fix this

**Comment by scott-w** [comment]
Hi @spenoir, thanks for contributing this. I think it's important that this library fails hard if Local Storage isn't supported in the user's browser.

As an alternative, I'd support providing an option that handles the lack of support to give the developer a choice on exactly how they'd like to handle it.

Hope this helps
Scott
