### ISSUE TITLE
Safari in private mode - QUOTA_EXCEEDED_ERR

### ISSUE THREAD

**Issue by ihor-sviziev** [jeromegn/Backbone.localStorage#171]
When I use Safari in private mode - when we use localStorage.setItem() - we getting exception. More details there: http://stackoverflow.com/questions/9077101/iphone-localstorage-quota-exceeded-err-issue

As result instead of "sync" event we getting "error" event in model. Would be great in this case save all data in array and do not fire error event.

iPad Air 2, iOS 8.1.3

**Comment by scott-w** [comment]
Hi @ihor-sviziev, I think that the issue is in Safari and the only thing this library can do is report an error.

The correct behaviour should be an error getting thrown at the very start, so we know that the issue is localStorage not being supported as early as possible.
