### ISSUE TITLE
Rename to BackboneStorage

### ISSUE THREAD

**Issue by hugohenrique** [jeromegn/Backbone.localStorage#191]
Hi!
What do you think is to rename StorageBackbone?
I believe it can become more semantic, if you need to use LocalStorage or SessionStorage.

``` javascript

Backbone.Storage = function () {
  // current implementation
};

Backbone.LocalStorage = Backbone.Storage;
Backbone.SessionStorage = Backbone.Storage;

Backbone.LocalStorage.prototype.storage = function () {
  return window.localStorage;
};

Backbone.SessionStorage.prototype.storage = function () {
  return window.sessionStorage;
};
```

**Comment by scott-w** [comment]
Hi @hugohenrique, while I like the suggestion I think keeping this focused on the `localStorage` implementation is the right way forward for now, given the limited resources available to the project.
