### ISSUE TITLE
Maintaining LocalStorage

### ISSUE THREAD

**Issue by scott-w** [jeromegn/Backbone.localStorage#204]
Hi @jeromegn,

I notice that you're not able to dedicate more time to maintaining the LocalStorage integration for Backbone.

I'd like to help maintain this repository as I make use of it for my personal projects and work-related projects. For background, I'm part of the MarionetteJS team and have worked with and maintained open source projects for at least 5 years now.

Could you let me know what would work best for you in terms of administration?

Regards,
Scott

**Comment by scott-w** [comment]
Hi @jeromegn, I appreciate you've likely been busy and haven't had a chance to reply.

For the benefit of others reading this, I've created a separate repository at https://github.com/scott-w/backbone.localstorage and I'm publishing an updated version of this (in ES6) to NPM as `backbone.local`.

I'm more than happy for anyone to open issues or Pull Requests to help get the project in a stable position for production use and I'll do my best to help anyone wanting to get involved.

I'd really like to hear from you to see if you're interested in taking any changes I make back into the mainline repository to continue publishing from the original name. I really appreciate all the work you've done over the years to maintain this project and would love to keep it going.

Best regards,
Scott

**Comment by jeromegn** [comment]
Hi Scott,

Good job on this. I'm glad you took the initiative to do it. Actions speak louder than words.

In light of these actions, I'd be happy to give you maintainer access to this repository if you're interesting in fixing the outstanding issues.

Using a different npm package is also fine! However, there are a lot more people who already have it configured for this package. Either way, I fully support your endeavour. (I do wish you'd have "forked" this repository though, it would've been easier to compare the two versions.)

Sorry for not replying earlier. I remember vaguely checking it out, but I have been both busy and out of the loop when it comes to Backbone and client-side development.

Let me know what you'd prefer doing.

**Comment by scott-w** [comment]
Hi @jeromegn,

Great to hear from you! I totally agree that re-using the existing repo + NPM package is the preferable option.

Regarding forking, that's totally fine, I can easily setup my `git remote` again to point at a newly forked repo 👍 

I'll leave the new package up for now, it's letting me test the changes I'm making to update the package before I can put them back into this repo.

If you can give me access rights to both this repo and the NPM repo I'm happy to maintain everything as-is.

Thanks again,
Scott

**Comment by jeromegn** [comment]
Done and done! 🎉
