### ISSUE TITLE
Disable console.log in LocalStorage

### ISSUE THREAD

**Issue by Bartosz-D3V** [jeromegn/Backbone.localStorage#213]
Hi,

I use LocalStorage and I find it incredibly useful when it comes to create modern web apps.
One thing that makes think is whether it is not be possible to disable auto-logging the operations that LocalStorage is performing?
In the source code the following chunk of code is responsible for logging operations into the console every time I add new object into LocalStorage:
```
if (resp) {
console.log(resp);
if (options.success) {
options.success.call(model, resp, options);
}
```

I cannot find any option to disable the console.log, could you please provide some guidance?

I use 2.0.0-alpha.2 version (provided by default on NPM).

Many thanks,
Bart

**Comment by scott-w** [comment]
Thanks for pointing this out @Bartosz-D3V - I've published Alpha 3 without the logging calls 👍
