### ISSUE TITLE
Backbone.Model.destroy() does not work the same as in Backbone.js

### ISSUE THREAD

**Issue by jDavidnet** [jeromegn/Backbone.localStorage#50]
In backbone.js if you use model.destroy() on an object it should delete it's reference on the server.

In this environment, it does not properly work.

WORKAROUND

model.destroy(model); seems to work in a few cases, if you have not created multiple versions of the model via #48

**Comment by spenoir** [comment]
so is adding the localStorage key to models recommended? It does work but it seems wrong and breaks a unit test I have written for karma
