### ISSUE TITLE
"model.set(model.idAttribute, guid())" fires second "change" event 

### ISSUE THREAD

**Issue by baklinger** [jeromegn/Backbone.localStorage#97]
When I try the first "save" for my model the "set" call inside the "create" function fires second "change" event on the model:

 if (!model.id) {
      model.id = guid();
      model.set(model.idAttribute, model.id);
    }

I think it's a bug but if it's necessary please explain how can I deal with this issue to avoid double call of "change" callback?

**Comment by almirfilho** [comment]
Any update about this issue?
